set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(NOT DEFINED RPI_SYSROOT OR RPI_SYSROOT STREQUAL "")
  get_filename_component(
    RPI_SYSROOT
    "${CMAKE_CURRENT_LIST_DIR}/../../sysroots/rpi-zero-2w"
    ABSOLUTE)
endif()

set(_RPI_SYSROOT_EFFECTIVE "${RPI_SYSROOT}")
if(EXISTS "${RPI_SYSROOT}/usr/usr/include" AND NOT EXISTS "${RPI_SYSROOT}/usr/include")
  set(_RPI_SYSROOT_EFFECTIVE "${RPI_SYSROOT}/usr")
endif()

set(CMAKE_SYSROOT "${_RPI_SYSROOT_EFFECTIVE}")

if(DEFINED ENV{CC} AND NOT "$ENV{CC}" STREQUAL "")
  set(CMAKE_C_COMPILER "$ENV{CC}" CACHE FILEPATH "" FORCE)
else()
  find_program(CMAKE_C_COMPILER NAMES aarch64-linux-gnu-gcc REQUIRED)
endif()

if(DEFINED ENV{CXX} AND NOT "$ENV{CXX}" STREQUAL "")
  set(CMAKE_CXX_COMPILER "$ENV{CXX}" CACHE FILEPATH "" FORCE)
else()
  find_program(CMAKE_CXX_COMPILER NAMES aarch64-linux-gnu-g++ REQUIRED)
endif()

if(DEFINED ENV{AR} AND NOT "$ENV{AR}" STREQUAL "")
  set(CMAKE_AR "$ENV{AR}" CACHE FILEPATH "" FORCE)
else()
  find_program(CMAKE_AR NAMES aarch64-linux-gnu-ar REQUIRED)
endif()

if(DEFINED ENV{RANLIB} AND NOT "$ENV{RANLIB}" STREQUAL "")
  set(CMAKE_RANLIB "$ENV{RANLIB}" CACHE FILEPATH "" FORCE)
else()
  find_program(CMAKE_RANLIB NAMES aarch64-linux-gnu-ranlib REQUIRED)
endif()

if(DEFINED ENV{STRIP} AND NOT "$ENV{STRIP}" STREQUAL "")
  set(CMAKE_STRIP "$ENV{STRIP}" CACHE FILEPATH "" FORCE)
else()
  find_program(CMAKE_STRIP NAMES aarch64-linux-gnu-strip REQUIRED)
endif()

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
if(DEFINED OPEN_SRC_INSTALL_PREFIX AND NOT OPEN_SRC_INSTALL_PREFIX STREQUAL "")
  list(APPEND CMAKE_FIND_ROOT_PATH "${OPEN_SRC_INSTALL_PREFIX}")
  list(APPEND CMAKE_PREFIX_PATH "${OPEN_SRC_INSTALL_PREFIX}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

set(_RPI_LINK_DIRS
  "${CMAKE_SYSROOT}/lib"
  "${CMAKE_SYSROOT}/lib/aarch64-linux-gnu"
  "${CMAKE_SYSROOT}/usr/lib"
  "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu")

foreach(_dir IN LISTS _RPI_LINK_DIRS)
  if(EXISTS "${_dir}")
    string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " -Wl,-rpath-link,${_dir}")
    string(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT " -Wl,-rpath-link,${_dir}")
  endif()
endforeach()

unset(_RPI_LINK_DIRS)
